### ISSUE TITLE
TypeError: Cannot read property 'startActivity' of undefined

### ISSUE THREAD

**Issue by A35G** [mobilemindtec/nativescript-extra-call#1]
I get this error if, once the plugin is installed, I try to use it as directed.... some hints?

**Comment by mobilemindtech** [comment]
Hi @A35G,

Can you provide more details? What is the operation?

**Comment by A35G** [comment]
I have followed this steps:

- Downloaded code from page

- Added plugin to project with:
`tns plugin add path_folder`

- declared into ***main-page.js***:
  `var ExtraCall = require("nativescript-extra-call");`

- and insert:

  `ExtraCall.withWhatsapp({
	message: "Nativescript plugin test",
	number: 0000000000
});`

 - and compiled with:
  `tns run android`

I obtain error as title

**Comment by mobilemindtech** [comment]
Hi,

I made a test running the demo and it work. I use this plugin in another projects too, the same version.

try execute this code directly in your page and debug when `context` is undefined:

```
    var application = require("application");

    var args = { number: '000000000', message: 'test' }

    var uri = android.net.Uri.parse("smsto:+" + args.number);
    var intent = new android.content.Intent(android.content.Intent.ACTION_SENDT, uri);
    intent.setType("text/plain");
    intent.setPackage("com.whatsapp");
    intent.putExtra(android.content.Intent.EXTRA_TEXT, args.message);
    intent.putExtra("chat",true);     
    intent.setFlags(android.content.Intent.FLAG_ACTIVITY_NO_HISTORY); 
   
    if (intent.resolveActivity(application.android.context.getPackageManager()) != null) {          
      application.android.currentContext.startActivity(intent);
    }else{
      //as not app whatsapp api
      var browserIntent = new android.content.Intent(android.content.Intent.ACTION_VIEW, 
       android.net.Uri.parse("market://details?id=com.whatsapp"));        
      application.android.currentContext.startActivity(browserIntent);        
    
    }
```

**Comment by A35G** [comment]
Use directly this code without plugin installed?

Explode everything xD

https://pastebin.com/qCRDWCkU

**Comment by mobilemindtech** [comment]
You don't need uninstall plugin. This code is part of plugin.. so you can debug where is undefined variable.

**Comment by A35G** [comment]
The errors reported on pastebin, I find them if you apply the code you have indicated to me, without installing the plugin

**Comment by mobilemindtech** [comment]
right, what is the   line code 314?

```
File: "file:///data/data/org.nativescript.myApp/files/app/main-page.js, line: 314, column: 40
```
this
```
application.android.currentContext
```
or 
```
application.android.current
```
should work

**Comment by A35G** [comment]
var application = require("application");

    var args = { number: '0000000000', message: 'test' }

    var uri = android.net.Uri.parse("smsto:+" + args.number);
    var intent = new android.content.Intent(android.content.Intent.ACTION_SENDT, uri);
    intent.setType("text/plain");
    intent.setPackage("com.whatsapp");
    intent.putExtra(android.content.Intent.EXTRA_TEXT, args.message);
    intent.putExtra("chat",true);     
    intent.setFlags(android.content.Intent.FLAG_ACTIVITY_NO_HISTORY); 
   
    if (intent.resolveActivity(application.android.context.getPackageManager()) != null) {          
      application.android.current.startActivity(intent);
    }else{
      //as not app whatsapp api
      var browserIntent = new android.content.Intent(android.content.Intent.ACTION_VIEW, 
       android.net.Uri.parse("market://details?id=com.whatsapp"));        
      application.android.current.startActivity(browserIntent);        
    
    }

Equal error;
line 314 is 
    
    application.android.currentContext.startActivity(intent);

Can there be any conflict?

**Comment by mobilemindtech** [comment]
Ok, changes to `application.android.context.startActivity(intent)` should work. You are calling this code in page `loaded` or `navigateTo` event?

**Comment by A35G** [comment]
In navigateTo event; outside I have this error:

    System.err: Error: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

But should I find the message in the history of the messages sent to that number?

**Comment by mobilemindtech** [comment]
You should call this code or plugin action in user event, like a tap button.. I believe that in this step (nativegaTo) `currentContext` has not yet been injected by nativescript. Demo plugin work fine, because execute action at tap button. Demo code https://github.com/mobilemindtec/nativescript-extra-call/tree/master/demo

Anyway I'll update the plugin for user always `context` and not `currentContext`.

**Comment by A35G** [comment]
Can't everything be recalled from another function without errors?

**Comment by mobilemindtech** [comment]
I do not understand very well what you need. But, WhatsApp is very limited to integrate.. see https://faq.whatsapp.com/en/android/28000012.  and ios is still more limited https://faq.whatsapp.com/en/iphone/23559013.
